# Generated by Django 3.1.7 on 2021-03-23 17:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_name', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='KitOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('web_address', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('shelf_number', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('IRB_number', models.CharField(max_length=50)),
                ('pet_name', models.CharField(max_length=50)),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('sponsor_name', models.CharField(max_length=100)),
                ('requisition_form_qty', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('Preparing to Open', 'Preparing to Open'), ('Open', 'Open'), ('Closed', 'Closed')], default='Preparing to Open', max_length=32)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True)),
                ('kit_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_orders', to='KITS.kitorder')),
            ],
            options={
                'ordering': ['IRB_number'],
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField(blank=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KITS.study')),
            ],
        ),
        migrations.CreateModel(
            name='KitInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular kit used in any Study', primary_key=True, serialize=False)),
                ('scanner_id', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Available'), ('c', 'Checked Out'), ('e', 'Expired'), ('d', 'Demolished')], default='a', help_text='Kit Availability', max_length=1)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='kit', to='KITS.kit')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='KITS.location')),
            ],
            options={
                'ordering': ['expiration_date'],
                'permissions': (('can_mark_demolished', 'Set kit as demolished'),),
            },
        ),
        migrations.AddField(
            model_name='kit',
            name='IRB_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='KITS.study'),
        ),
    ]
