# Generated by Django 3.1.7 on 2021-02-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KITS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitorder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
