# Generated by Django 3.1.7 on 2021-03-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KITS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='type_name',
            field=models.CharField(blank=True, choices=[('Screening', 'Screening'), ('Day 1', 'Day 1'), ('Day 30', 'Day 30')], max_length=32),
        ),
    ]
